### ISSUE TITLE
USB/Bluetooth keyboard

### ISSUE THREAD

**Issue by F1LT3R** [dixonary/fingerterm-reMarkable#1]
Is it possible to use a USB/Bluetooth keyboard with fingerterm?

**Comment by dixonary** [comment]
I don't know. I suspect that the USB does not have HID enabled for input as
it's intended as a touchscreen device. It does not support Bluetooth.

**Comment by ddvk** [comment]
> Is it possible to use a USB/Bluetooth keyboard with fingerterm?

yes it is possible to use an usb bt dongle, but you need to compile and load bluetooth support and the bluez package

**Comment by dixonary** [comment]
Thanks ddvk. I'll close this for now as it's out of scope for fingerterm.

**Comment by qubist** [comment]
A related question: If a keyboard is successfully connected, will keyboard presses be recognized by fingerterm?
