### ISSUE TITLE
compatible with type folio?

### ISSUE THREAD

**Issue by HalosGhost** [dixonary/fingerterm-reMarkable#11]
I've heard a lot of buzz about the new [type folio](https://remarkable.com/store/remarkable-2/type-folio), but I've not heard any information about whether or not the folio is functional as a keyboard outside xochitl. In particular, I'm interested to know if it will work with fingerterm (since, if it does, it'd instantly turn the rm2 into an—admittedly odd—e-ink linux laptop). I've been weighing whether or not to get one, but I've not been able to find any information on this front.

Any chance you know if the type folio will function out-of-the-box with fingerterm (or, if not, do you have any plans to add explicit support for it)?

**Comment by dixonary** [comment]
That's a great question - I'm afraid that I do not know. I didn't deliberately disable any built-in fingerterm behaviour around physical keyboards, but I also don't know if it comes with any by default. It also depends on how the type folio interfaces with the machine (if it's using GPIO pins there's a good chance it's not standard).

fingerterm-reMarkable hasn't been updated in quite some time and it's not actively supported, but you're very welcome to try it!
